# Generated by Django 2.1.2 on 2018-10-20 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(default='')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(default='', max_length=15)),
                ('description', models.TextField()),
                ('standard_price', models.FloatField(default=0.0)),
                ('list_price', models.FloatField(default=0.0)),
                ('purchase_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('qty', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('min_qty', models.DecimalField(decimal_places=1, max_digits=4)),
                ('max_qty', models.DecimalField(decimal_places=1, max_digits=6)),
                ('pic_l', models.ImageField(height_field=500, null=True, upload_to='products', width_field=500)),
                ('pic_s', models.ImageField(height_field=200, null=True, upload_to='products', width_field=200)),
                ('product_size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('N', 'NA')], max_length=1)),
                ('colour', models.CharField(choices=[('BL', 'Black'), ('WH', 'White'), ('BU', 'Blue'), ('GR', 'Grey'), ('GR', 'Green')], max_length=1)),
                ('weight', models.FloatField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='category',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
